export interface FarmingSession {
  _id: string // auto-generated by Convex
  userId: string // Clerk user ID

  // Core info
  sessionName: string
  sessionDescription: string
  sessionNotes: string
  createdAt: number // Date.now()
  updatedAt: number

  // Mapping strategy details
  mapName: string // either user input or "random" if isRandomMap is true
  isRandomMap: boolean
  isOriginator: boolean
  isSelfFarmed: boolean
  mapCost: number | null // null if isSelfFarmed is true
  numberOfMaps: number

  // Chisels
  usingChisels: boolean
  chiselName?: string
  chiselPrice?: number // per unit

  // Scarabs (max length 5)
  usingScarabs: boolean
  scarabs: {
    name: string
    quantity: number // sum of all cannot exceed 5
    price: number // per unit
  }[]

  // Map device craft
  usingMapCraft: boolean
  mapCraftName?: string
  mapCraftPrice?: number

  // Calculated fields (you may cache these for convenience/UI performance)
  totalCost: number // computed as per your formula
  summary: {
    mapCostTotal: number
    chiselCostTotal: number
    scarabCostTotal: number
    craftCostTotal: number
  }

  // Session state
  isConcluded: boolean
  rawReturns?: number // added when concluding session
  timerHistory: {
    start: number
    end: number | null // null means currently running
    duration: number // derived, can be stored or computed on the fly
  }[]
}
