export const SCARAB_NAMES = [
  'Abyss Scarab',
  'Abyss Scarab of Edifice',
  'Abyss Scarab of Multitudes',
  'Abyss Scarab of Profound Depth',
  'Ambush Scarab',
  'Ambush Scarab of Containment',
  'Ambush Scarab of Discernment',
  'Ambush Scarab of Hidden Compartments',
  'Ambush Scarab of Potency',
  'Anarchy Scarab',
  'Anarchy Scarab of Gigantification',
  'Anarchy Scarab of Partnership',
  'Bestiary Scarab',
  'Bestiary Scarab of Duplicating',
  'Bestiary Scarab of the Herd',
  'Betrayal Scarab',
  'Betrayal Scarab of Reinforcements',
  'Betrayal Scarab of the Allflame',
  'Beyond Scarab',
  'Beyond Scarab of Haemophilia',
  'Beyond Scarab of Resurgence',
  'Beyond Scarab of the Invasion',
  'Blight Scarab',
  'Blight Scarab of Blooming',
  'Blight Scarab of Invigoration',
  'Blight Scarab of the Blightheart',
  'Breach Scarab',
  'Breach Scarab of Lordship',
  'Breach Scarab of Resonant Cascade',
  'Breach Scarab of Snares',
  'Breach Scarab of Splintering',
  'Cartography Scarab of Corruption',
  'Cartography Scarab of Escalation',
  'Cartography Scarab of Risk',
  'Cartography Scarab of the Multitude',
  'Delirium Scarab',
  'Delirium Scarab of Delusions',
  'Delirium Scarab of Mania',
  'Delirium Scarab of Neuroses',
  'Delirium Scarab of Paranoia',
  'Divination Scarab of Pilfering',
  'Divination Scarab of Plenty',
  'Divination Scarab of The Cloister',
  'Domination Scarab',
  'Domination Scarab of Apparitions',
  'Domination Scarab of Evolution',
  'Domination Scarab of Terrors',
  'Essence Scarab',
  'Essence Scarab of Adaptation',
  'Essence Scarab of Ascent',
  'Essence Scarab of Calcification',
  'Essence Scarab of Stability',
  'Expedition Scarab',
  'Expedition Scarab of Archaeology',
  'Expedition Scarab of Runefinding',
  'Expedition Scarab of Verisium Powder',
  'Harbinger Scarab',
  'Harbinger Scarab of Obelisks',
  'Harbinger Scarab of Regency',
  'Harbinger Scarab of Warhoards',
  'Harvest Scarab',
  'Harvest Scarab of Cornucopia',
  'Harvest Scarab of Doubling',
  'Horned Scarab of Awakening',
  'Horned Scarab of Bloodlines',
  'Horned Scarab of Glittering',
  'Horned Scarab of Nemeses',
  'Horned Scarab of Pandemonium',
  'Horned Scarab of Preservation',
  'Horned Scarab of Tradition',
  'Incursion Scarab',
  'Incursion Scarab of Champions',
  'Incursion Scarab of Invasion',
  'Incursion Scarab of Timelines',
  'Influencing Scarab of Conversion',
  'Influencing Scarab of Hordes',
  'Influencing Scarab of the Elder',
  'Influencing Scarab of the Shaper',
  'Kalguuran Scarab',
  'Kalguuran Scarab of Guarded Riches',
  'Kalguuran Scarab of Refinement',
  'Legion Scarab',
  'Legion Scarab of Command',
  'Legion Scarab of Eternal Conflict',
  'Legion Scarab of Officers',
  'Ritual Scarab of Abundance',
  'Ritual Scarab of Selectiveness',
  'Ritual Scarab of Wisps',
  'Scarab of Adversaries',
  'Scarab of Bisection',
  'Scarab of Divinity',
  'Scarab of Hunted Traitors',
  'Scarab of Monstrous Lineage',
  'Scarab of Radiant Storms',
  'Scarab of Stability',
  'Scarab of Wisps',
  'Sulphite Scarab',
  'Sulphite Scarab of Fumes',
  'Titanic Scarab',
  'Titanic Scarab of Legend',
  'Titanic Scarab of Treasures',
  'Torment Scarab',
  'Torment Scarab of Peculiarity',
  'Torment Scarab of Possession',
  'Ultimatum Scarab',
  'Ultimatum Scarab of Bribing',
  'Ultimatum Scarab of Catalysing',
  'Ultimatum Scarab of Dueling',
  'Ultimatum Scarab of Inscription',
]
